ProjetoFilmes.MVC/Models/ErrorViewModel.cs
namespace ProjetoFilmes.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoFilmes.MVC/Controllers/FilmesController.cs
using System.Net;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoFilmes.LIB.Models;

namespace ProjetoFilmes.MVC.Controllers
{
    public class FilmesController : Controller
    {
        string Baseurl = "http://localhost:5125/api/filmes/";

        // GET: FilmesController
        public async Task<IActionResult> Index()
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                var todosFilmes = await client.GetFromJsonAsync<List<Filme>>("");

                return View(todosFilmes);
            }
        }

        // GET: FilmesController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                var Filme = await client.GetFromJsonAsync<Filme>(id.ToString());

                return View(Filme);
            }

        }

        // GET: FilmesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FilmesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(/*IFormCollection collection*/ Filme filme)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);

                    await client.PostAsJsonAsync<Filme>("", filme);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return View(filme);
            }
        }

        // GET: FilmesController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                var Filme = await client.GetFromJsonAsync<Filme>(id.ToString());

                return View(Filme);
            }
        }

        // POST: FilmesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("FilmeID, Titulo, DataLancamento")] Filme filme)
        {
            if (filme == null)
            {
                return NotFound();
            }

            //checking model state
            if (ModelState.IsValid)
            {
                try
                {
                    using (HttpClient client = new HttpClient())
                    {
                        filme.FilmeID = id;

                        client.BaseAddress = new Uri(Baseurl);
                        //HTTP PUT
                        var result = await client.PutAsJsonAsync<Filme>(id.ToString(), filme);

                        if (result.IsSuccessStatusCode)
                        {
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    return View(filme);
                }
                catch
                {
                    return View(filme);
                }
            }
            return View(filme);
        }

        // GET: FilmesController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                var Filme = await client.GetFromJsonAsync<Filme>(id.ToString());

                return View(Filme);
            }
        }

        // POST: FilmesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, /*IFormCollection collection*/ Filme filme)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    await client.DeleteAsync(id.ToString());

                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoFilmes.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetoFilmes.MVC.Models;

namespace ProjetoFilmes.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoFilmes.MVC/Views/Filmes/Create.cshtml
@using ProjetoFilmes.LIB.Models;
@model ProjetoFilmes.LIB.Models.Filme

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <select asp-for="Genero" class="form-control" asp-items="Html.GetEnumSelectList<Genero>()"></select>
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoFilmes.MVC/Views/Filmes/Delete.cshtml
@model ProjetoFilmes.LIB.Models.Filme

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvaliacaoAvg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvaliacaoAvg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjetoFilmes.MVC/Views/Filmes/Details.cshtml
@model ProjetoFilmes.LIB.Models.Filme

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilmeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilmeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvaliacaoAvg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvaliacaoAvg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FilmeID}) |
    <a asp-action="Index">Back to List</a>
</div>

ProjetoFilmes.MVC/Views/Filmes/Edit.cshtml
@model ProjetoFilmes.LIB.Models.Filme

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvaliacaoAvg" class="control-label"></label>
                <input asp-for="AvaliacaoAvg" class="form-control" />
                <span asp-validation-for="AvaliacaoAvg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoFilmes.MVC/Views/Filmes/Index.cshtml
@model IEnumerable<ProjetoFilmes.LIB.Models.Filme>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FilmeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataLancamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvaliacaoAvg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FilmeID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataLancamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AvaliacaoAvg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genero)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.FilmeID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.FilmeID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.FilmeID })
                </td>
            </tr>
        }
    </tbody>
</table>

ProjetoFilmes.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetoFilmes.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoFilmes.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoFilmes.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoFilmes.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Index">Filmes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetoFilmes.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>